# Generated by Django 3.0.2 on 2020-01-05 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('stage_name', models.TextField()),
                ('year_of_birth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file_name', models.TextField()),
                ('content_type', models.TextField()),
                ('size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('release_date', models.DateField()),
                ('duration', models.DurationField()),
                ('lyrics', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='yamod.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yamod.Country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('a', 'Action'), ('c', 'Comedy')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='maps',
            field=models.ManyToManyField(blank=True, to='yamod.Media'),
        ),
        migrations.AddField(
            model_name='movie',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='yamod.Media'),
        ),
        migrations.AddField(
            model_name='person',
            name='lebenslauf',
            field=models.ManyToManyField(blank=True, to='yamod.Media'),
        ),
    ]
