# Generated by Django 3.0.2 on 2020-01-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0003_auto_20200106_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='email',
            field=models.EmailField(default='template@email.org', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='year_of_birth',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
